package com.kieran.projects.haydayprofitabilityhelper.api.entity;

public enum Source {

    CROP, SUGAR_MILL, CAKE_OVEN, DAIRY_MACHINE,
    BAKERY, JUICE_PRESS, PIE_OVEN, JAM_MAKER,
    LOOM, SEWING_MACHINE, JEWELER, GRILL, POPCORN_MAKER,
    FEED_MILL, CHICKEN, COW, PIG, SHEEP, GOAT, SMELTER,
    TREE, BUSH, MINE, ICE_CREAM_MAKER, HONEY_EXTRACTOR,
    COFFEE_KIOSK, SOUP_KITCHEN, CANDLE_MAKER, FLOWER_SHOP,
    SAUCE_MAKER, CANDY_MACHINE, SUSHI_BAR, SALAD_BAR, SANDWICH_BAR,
    SMOOTHIE_MIXER, PASTA_MAKER, ESSENTIAL_OILS_LAB, WOK_KITCHEN,
    HAT_MAKER, PASTA_KITCHEN, HOT_DOG_STAND, DONUT_MAKER, TACO_KITCHEN,
    OMELET_STATION, TEA_STAND, FONDUE_POT, BATH_KIOSK, DEEP_FRYER, POTTERY_STUDIO,
    PRESERVATION_KITCHEN, FUDGE_SHOP, YOGURT_MAKER, CUPCAKE_MAKER, STEW_POT,
    WAFFLE_MAKER, PORRIDGE_BAR, MILKSHAKE_BAR

}